### ISSUE TITLE
Sound files?

### ISSUE THREAD

**Issue by xtra-chromosomes** [gorescript/gorescript#15]
Where are the music and sound effect file locations, i was gonna do some sick switching of the files to have a more "entertaining" experience to my personal game.

**Comment by SyntaxStacks** [comment]
It's in the readme but it doesn't seem that the assets have been bundled in the past couple of releases. Here's a link to the latest [Assets](https://github.com/gorescript/gorescript/releases/download/v1.1/assets.zip)
