### ISSUE TITLE
No Executable Application

### ISSUE THREAD

**Issue by MorganFreedman** [gorescript/gorescript#16]
I am trying to mod the game with a friend but we don't have the knowledge to create our own application. I am wondering if by chance you do and if not then it is okay.

**Comment by SyntaxStacks** [comment]
the (gulpfile)[https://github.com/gorescript/gorescript/blob/master/gulpfile.js] has a few different ways to build the app

**Comment by sergiubucur** [comment]
The steps to build it are:

- Download the repository
- Download the assets zip from [here](https://github.com/gorescript/gorescript/releases/download/v1.1/assets.zip)
- Unpack the assets to the \src\game folder (so the \src\game folder should now contain an \assets folder)
- Install Node.js
- Open a command line window, go to the root folder of the repository
- Run the commands:
        `npm install gulp -g`
        `npm install`
        `gulp web-debug`
- When it says "finished js-client" hit CTRL+C and terminate it
- Go to the newly created \dist folder (in the root of the repository)
- Run the commands:
        `npm install http-server -g`
        `http-server`

http://localhost:8080 should now contain a playable version of the game.
